name: CI

on:
  push:
    branches: # only for pushes on main
      - main
  pull_request: # for all PRs regardless of its base branch

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
        id: go

      - name: Checkout code into the Go module directory
        uses: actions/checkout@v2

      - name: Tidy
        run: |
          rm -f go.sum
          go mod tidy -go=1.16 && go mod tidy -go=1.17

      - name: Build
        env:
          GO: go
        run: make build

      - name: Run unit tests
        env:
          GO: go
        run: make test

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.30
